# Generated by Django 4.0.5 on 2022-07-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='product/images')),
            ],
        ),
    ]
