# Generated by Django 4.0.5 on 2022-07-22 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_order_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
    ]
