# Generated by Django 4.0.5 on 2022-07-24 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_product_order_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
