# Generated by Django 4.0.5 on 2022-07-29 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='order_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='order_phone',
        ),
    ]
